<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_Q6IGIKY3EfGXZucFURQGfA" name="RescueSync_BPM" bonitaModelVersion="9">
    <elements xmi:type="process:Pool" xmi:id="_8odVAKY8EfGXZucFURQGfA" name="Proceso de Gestion de Emergencia RescueSync" displayName="Proceso RescueSync">
      <elements xmi:type="process:Lane" xmi:id="_AX4iMKY_EfGXZucFURQGfA" name="Operador Municipal" actor="_yhzSAKu2EfGXZucFURQGfA">
        <elements xmi:type="process:StartEvent" xmi:id="_jyTMYKY_EfGXZucFURQGfA" name="Registro de Emergencia" outgoing="_RMEboKZAEfGXZucFURQGfA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jyVBkaY_EfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jyVBkKY_EfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jyVBkqY_EfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_QPvWQKZAEfGXZucFURQGfA" name="Registrar Emergencia" outgoing="_3-C3gKZAEfGXZucFURQGfA" incoming="_RMEboKZAEfGXZucFURQGfA" actor="_yhzSAKu2EfGXZucFURQGfA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QPv9UaZAEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QPv9UKZAEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QPv9UqZAEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_QPv9U6ZAEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_QPv9VKZAEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QPv9VaZAEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QPv9V6ZAEfGXZucFURQGfA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QPv9VqZAEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_QPv9WaZAEfGXZucFURQGfA">
            <targetForm xmi:type="expression:Expression" xmi:id="_QPv9WqZAEfGXZucFURQGfA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_QPv9WKZAEfGXZucFURQGfA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_QPv9W6ZAEfGXZucFURQGfA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_B-ZogKZJEfGXZucFURQGfA" name="Seleccionar y Adjudicar Ofertas" outgoing="_PWPVcKuxEfGXZucFURQGfA" incoming="_MA-gsKZJEfGXZucFURQGfA" actor="_yhzSAKu2EfGXZucFURQGfA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_B-ZogqZJEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_B-ZogaZJEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_B-Zog6ZJEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_B-ZohKZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_B-ZohaZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_B-ZohqZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_B-ZoiKZJEfGXZucFURQGfA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_B-Zoh6ZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_B-ZoiqZJEfGXZucFURQGfA">
            <targetForm xmi:type="expression:Expression" xmi:id="_B-Zoi6ZJEfGXZucFURQGfA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_B-ZoiaZJEfGXZucFURQGfA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_B-ZojKZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_I-J0cKY_EfGXZucFURQGfA" name="Centro Coordinador Regional" actor="_CW-a8Ku3EfGXZucFURQGfA">
        <elements xmi:type="process:Task" xmi:id="_wxtMoKZAEfGXZucFURQGfA" name="Revisar informacion y desglosar en Lotes de Necesidades(cuenta como manual?)" outgoing="_2gVt8KZBEfGXZucFURQGfA" incoming="_3-C3gKZAEfGXZucFURQGfA _FnCYkKZIEfGXZucFURQGfA" actor="_CW-a8Ku3EfGXZucFURQGfA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wxtMoqZAEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wxtMoaZAEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wxtMo6ZAEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_wxtMpKZAEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_wxtMpaZAEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_wxtMpqZAEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_wxtMqKZAEfGXZucFURQGfA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_wxtMp6ZAEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_wxtMqqZAEfGXZucFURQGfA">
            <targetForm xmi:type="expression:Expression" xmi:id="_wxtMq6ZAEfGXZucFURQGfA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_wxtMqaZAEfGXZucFURQGfA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_wxtMrKZAEfGXZucFURQGfA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_XZo-4KZFEfGXZucFURQGfA" name="Decidir Curso de Accion" outgoing="_wHHTUKZHEfGXZucFURQGfA" incoming="_cA420KZFEfGXZucFURQGfA" actor="_CW-a8Ku3EfGXZucFURQGfA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XZo-4qZFEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XZo-4aZFEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XZo-46ZFEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_X0Y7kKuzEfGXZucFURQGfA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_X0Y7kauzEfGXZucFURQGfA" name="opcionElegida" content="opcionElegida" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_bt4VoKuzEfGXZucFURQGfA" documentation="opcion que elige el Coordinador" name="opcionElegida" dataType="_Q6IGUaY3EfGXZucFURQGfA"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_X0Y7kquzEfGXZucFURQGfA" name="inputDecision" content="inputDecision" type="TYPE_CONTRACT_INPUT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_dnXm0KuzEfGXZucFURQGfA" name="inputDecision">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_dnXm0auzEfGXZucFURQGfA"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_X0Y7k6uzEfGXZucFURQGfA" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_XZo-5KZFEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_XZo-5aZFEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_XZo-5qZFEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_XZo-6KZFEfGXZucFURQGfA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_XZo-56ZFEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_XZo-6qZFEfGXZucFURQGfA">
            <targetForm xmi:type="expression:Expression" xmi:id="_XZo-66ZFEfGXZucFURQGfA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_XZo-6aZFEfGXZucFURQGfA">
            <inputs xmi:type="process:ContractInput" xmi:id="_R3zBUKuzEfGXZucFURQGfA" name="inputDecision">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_R3zBUauzEfGXZucFURQGfA"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_XZo-7KZFEfGXZucFURQGfA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_WxIigKZHEfGXZucFURQGfA" name="Publicar oficialmente la convocatoria ?" outgoing="_Mus0QKZHEfGXZucFURQGfA" incoming="_2gVt8KZBEfGXZucFURQGfA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yVPmgaZBEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yVPmgKZBEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yVPmgqZBEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_yVPmg6ZBEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_yVPmhKZBEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_yVPmhaZBEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_yVPmh6ZBEfGXZucFURQGfA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_yVPmhqZBEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_vO4q0KZHEfGXZucFURQGfA" name="Decision que toma el coordinador" outgoing="_9JfkgKZHEfGXZucFURQGfA _FnCYkKZIEfGXZucFURQGfA _oQA-wKZIEfGXZucFURQGfA" incoming="_wHHTUKZHEfGXZucFURQGfA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vO5R4aZHEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vO5R4KZHEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vO5R4qZHEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_NW-O0KY_EfGXZucFURQGfA" name="Representante de ONG" actor="_JrQg4Ku3EfGXZucFURQGfA">
        <elements xmi:type="process:Task" xmi:id="_tkp6cKZDEfGXZucFURQGfA" name="Cargar Ofertas de Ayuda" incoming="_Mus0QKZHEfGXZucFURQGfA _9JfkgKZHEfGXZucFURQGfA" actor="_JrQg4Ku3EfGXZucFURQGfA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tkqhgaZDEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tkqhgKZDEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tkqhgqZDEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_tkqhg6ZDEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_tkqhhKZDEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_tkqhhaZDEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_tkqhh6ZDEfGXZucFURQGfA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_tkqhhqZDEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_4Cca8KfjEfGXZucFURQGfA" name="Temporizador Carga de Ofertas" outgoing="_Fg5kIKfkEfGXZucFURQGfA">
            <condition xmi:type="expression:Expression" xmi:id="_PT4WQKu3EfGXZucFURQGfA" name="7 días: 00:00:00" content="604800000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_tkqhiaZDEfGXZucFURQGfA">
            <targetForm xmi:type="expression:Expression" xmi:id="_tkqhiqZDEfGXZucFURQGfA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_tkqhiKZDEfGXZucFURQGfA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_tkqhi6ZDEfGXZucFURQGfA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_EhLrIKZFEfGXZucFURQGfA" name="Evaluar Cobertura de Lotes" outgoing="_cA420KZFEfGXZucFURQGfA _r9DRMKZIEfGXZucFURQGfA" incoming="_qkHk0KZHEfGXZucFURQGfA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EhLrIqZFEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EhLrIaZFEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EhLrI6ZFEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_XnSHYKZHEfGXZucFURQGfA" name="Solicitar Listado Consolidado de Ofertas" outgoing="_qkHk0KZHEfGXZucFURQGfA" incoming="_Fg5kIKfkEfGXZucFURQGfA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xTvl4qZEEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xTvl4aZEEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xTvl46ZEEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xTvl5KZEEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xTvl5aZEEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xTvl5qZEEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xTvl6KZEEfGXZucFURQGfA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xTvl56ZEEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_mho78KZJEfGXZucFURQGfA" name="Recibe notificacion y marca actividades finalizadas" outgoing="_04DA0KZJEfGXZucFURQGfA" incoming="_pYIA4KZJEfGXZucFURQGfA" actor="_JrQg4Ku3EfGXZucFURQGfA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_mho78qZJEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_mho78aZJEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_mho786ZJEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_mho79KZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_mho79aZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_mho79qZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_mho7-KZJEfGXZucFURQGfA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_mho796ZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_mho7-qZJEfGXZucFURQGfA">
            <targetForm xmi:type="expression:Expression" xmi:id="_mho7-6ZJEfGXZucFURQGfA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_mho7-aZJEfGXZucFURQGfA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_mho7_KZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_P_phQKY_EfGXZucFURQGfA" name="Sistema Nacional">
        <elements xmi:type="process:ServiceTask" xmi:id="_hdcewKZIEfGXZucFURQGfA" name="Validacion Externa" outgoing="_MA-gsKZJEfGXZucFURQGfA" incoming="_oQA-wKZIEfGXZucFURQGfA _r9DRMKZIEfGXZucFURQGfA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_hdcewqZIEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_hdcewaZIEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_hdcew6ZIEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_hdcexKZIEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_hdcexaZIEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_hdcexqZIEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_hdceyKZIEfGXZucFURQGfA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_hdcex6ZIEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_XqdFQKZJEfGXZucFURQGfA" name="Registrar Compromiso Nacional" outgoing="_pYIA4KZJEfGXZucFURQGfA" incoming="_PWPVcKuxEfGXZucFURQGfA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XqdsUaZJEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XqdsUKZJEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XqdsUqZJEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_XqdsU6ZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_XqdsVKZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_XqdsVaZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_XqdsV6ZJEfGXZucFURQGfA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_XqdsVqZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_yiNK0KZJEfGXZucFURQGfA" name="Liberar Recursos" outgoing="_9CkLMKZJEfGXZucFURQGfA" incoming="_04DA0KZJEfGXZucFURQGfA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yiNx4aZJEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yiNx4KZJEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yiNx4qZJEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_yiNx46ZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_yiNx5KZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_yiNx5aZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_yiNx56ZJEfGXZucFURQGfA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_yiNx5qZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_3eEn4KZJEfGXZucFURQGfA" name="Fin del Proceso" incoming="_9CkLMKZJEfGXZucFURQGfA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3eFO8aZJEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3eFO8KZJEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3eFO8qZJEfGXZucFURQGfA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_MgflcKuzEfGXZucFURQGfA" documentation="opcion que elige el Coordinador" name="opcionElegida" dataType="_Q6IGUaY3EfGXZucFURQGfA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_MgflcauzEfGXZucFURQGfA" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_hAJ1oKu1EfGXZucFURQGfA" name="lotesCubiertos" dataType="_Q6IGTKY3EfGXZucFURQGfA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_hAJ1oau1EfGXZucFURQGfA" content="" returnType="java.lang.Boolean"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_8okCsKY8EfGXZucFURQGfA">
        <targetForm xmi:type="expression:Expression" xmi:id="_8okCsaY8EfGXZucFURQGfA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_8okCsqY8EfGXZucFURQGfA">
        <targetForm xmi:type="expression:Expression" xmi:id="_8okCs6Y8EfGXZucFURQGfA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RMEboKZAEfGXZucFURQGfA" target="_QPvWQKZAEfGXZucFURQGfA" source="_jyTMYKY_EfGXZucFURQGfA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RMFpwKZAEfGXZucFURQGfA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RMFpwaZAEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3-C3gKZAEfGXZucFURQGfA" target="_wxtMoKZAEfGXZucFURQGfA" source="_QPvWQKZAEfGXZucFURQGfA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3-C3gaZAEfGXZucFURQGfA"/>
        <condition xmi:type="expression:Expression" xmi:id="_3-C3gqZAEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2gVt8KZBEfGXZucFURQGfA" target="_WxIigKZHEfGXZucFURQGfA" source="_wxtMoKZAEfGXZucFURQGfA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2gVt8aZBEfGXZucFURQGfA"/>
        <condition xmi:type="expression:Expression" xmi:id="_2gVt8qZBEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cA420KZFEfGXZucFURQGfA" name="No se cubren Lotes" target="_XZo-4KZFEfGXZucFURQGfA" source="_EhLrIKZFEfGXZucFURQGfA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cA5d4KZFEfGXZucFURQGfA"/>
        <condition xmi:type="expression:Expression" xmi:id="_cA5d4aZFEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Mus0QKZHEfGXZucFURQGfA" target="_tkp6cKZDEfGXZucFURQGfA" source="_WxIigKZHEfGXZucFURQGfA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MuuCYKZHEfGXZucFURQGfA"/>
        <condition xmi:type="expression:Expression" xmi:id="_MuuCYaZHEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qkHk0KZHEfGXZucFURQGfA" target="_EhLrIKZFEfGXZucFURQGfA" source="_XnSHYKZHEfGXZucFURQGfA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qkHk0aZHEfGXZucFURQGfA"/>
        <condition xmi:type="expression:Expression" xmi:id="_qkHk0qZHEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wHHTUKZHEfGXZucFURQGfA" target="_vO4q0KZHEfGXZucFURQGfA" source="_XZo-4KZFEfGXZucFURQGfA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wHHTUaZHEfGXZucFURQGfA"/>
        <condition xmi:type="expression:Expression" xmi:id="_wHHTUqZHEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_9JfkgKZHEfGXZucFURQGfA" name="Reabrir Convocatoria" target="_tkp6cKZDEfGXZucFURQGfA" source="_vO4q0KZHEfGXZucFURQGfA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_9JfkgaZHEfGXZucFURQGfA"/>
        <condition xmi:type="expression:Expression" xmi:id="_9JfkgqZHEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FnCYkKZIEfGXZucFURQGfA" name="Revisar Informacion" target="_wxtMoKZAEfGXZucFURQGfA" source="_vO4q0KZHEfGXZucFURQGfA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FnC_oKZIEfGXZucFURQGfA"/>
        <condition xmi:type="expression:Expression" xmi:id="_FnDmsKZIEfGXZucFURQGfA" name="newScript()" content="opcionElegida == &quot;revisarInformacion&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_5mfusKu0EfGXZucFURQGfA" documentation="opcion que elige el Coordinador" name="opcionElegida" dataType="_Q6IGUaY3EfGXZucFURQGfA"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oQA-wKZIEfGXZucFURQGfA" name="Continuar con cobertura parcial" target="_hdcewKZIEfGXZucFURQGfA" source="_vO4q0KZHEfGXZucFURQGfA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oQA-waZIEfGXZucFURQGfA"/>
        <condition xmi:type="expression:Expression" xmi:id="_oQA-wqZIEfGXZucFURQGfA" name="newScript()" content="opcionElegida == &quot;coberturaParcial&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_TFJ6YKu1EfGXZucFURQGfA" documentation="opcion que elige el Coordinador" name="opcionElegida" dataType="_Q6IGUaY3EfGXZucFURQGfA"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_r9DRMKZIEfGXZucFURQGfA" name="Se cubren Lotes" target="_hdcewKZIEfGXZucFURQGfA" source="_EhLrIKZFEfGXZucFURQGfA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_r9D4QKZIEfGXZucFURQGfA"/>
        <condition xmi:type="expression:Expression" xmi:id="_r9D4QaZIEfGXZucFURQGfA" name="lotesCubiertosScript()" content="lotesCubiertos == &quot;true&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_hm86cKu2EfGXZucFURQGfA" name="lotesCubiertos" dataType="_Q6IGTKY3EfGXZucFURQGfA"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MA-gsKZJEfGXZucFURQGfA" target="_B-ZogKZJEfGXZucFURQGfA" source="_hdcewKZIEfGXZucFURQGfA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MA-gsaZJEfGXZucFURQGfA"/>
        <condition xmi:type="expression:Expression" xmi:id="_MA-gsqZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pYIA4KZJEfGXZucFURQGfA" target="_mho78KZJEfGXZucFURQGfA" source="_XqdFQKZJEfGXZucFURQGfA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pYIn8KZJEfGXZucFURQGfA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pYIn8aZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_04DA0KZJEfGXZucFURQGfA" target="_yiNK0KZJEfGXZucFURQGfA" source="_mho78KZJEfGXZucFURQGfA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_04DA0aZJEfGXZucFURQGfA"/>
        <condition xmi:type="expression:Expression" xmi:id="_04DA0qZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_9CkLMKZJEfGXZucFURQGfA" target="_3eEn4KZJEfGXZucFURQGfA" source="_yiNK0KZJEfGXZucFURQGfA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_9CkLMaZJEfGXZucFURQGfA"/>
        <condition xmi:type="expression:Expression" xmi:id="_9CkLMqZJEfGXZucFURQGfA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Fg5kIKfkEfGXZucFURQGfA" target="_XnSHYKZHEfGXZucFURQGfA" source="_4Cca8KfjEfGXZucFURQGfA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Fg6yQKfkEfGXZucFURQGfA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Fg8AYKfkEfGXZucFURQGfA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PWPVcKuxEfGXZucFURQGfA" target="_XqdFQKZJEfGXZucFURQGfA" source="_B-ZogKZJEfGXZucFURQGfA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PWS_0KuxEfGXZucFURQGfA"/>
        <condition xmi:type="expression:Expression" xmi:id="_PWVcEKuxEfGXZucFURQGfA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_7FolcKY-EfGXZucFURQGfA" name="Actor1"/>
      <actors xmi:type="process:Actor" xmi:id="_yhzSAKu2EfGXZucFURQGfA" name="Operador Municipal"/>
      <actors xmi:type="process:Actor" xmi:id="_CW-a8Ku3EfGXZucFURQGfA" name="Coordinador Regional"/>
      <actors xmi:type="process:Actor" xmi:id="_JrQg4Ku3EfGXZucFURQGfA" name="Representante ONG"/>
      <contract xmi:type="process:Contract" xmi:id="_8okCtKY8EfGXZucFURQGfA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8ojboKY8EfGXZucFURQGfA">
        <name xmi:type="expression:Expression" xmi:id="_8ojboaY8EfGXZucFURQGfA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8ojboqY8EfGXZucFURQGfA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8ojbo6Y8EfGXZucFURQGfA">
        <name xmi:type="expression:Expression" xmi:id="_8ojbpKY8EfGXZucFURQGfA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8ojbpaY8EfGXZucFURQGfA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8ojbpqY8EfGXZucFURQGfA">
        <name xmi:type="expression:Expression" xmi:id="_8ojbp6Y8EfGXZucFURQGfA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8ojbqKY8EfGXZucFURQGfA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8ojbqaY8EfGXZucFURQGfA">
        <name xmi:type="expression:Expression" xmi:id="_8ojbqqY8EfGXZucFURQGfA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8ojbq6Y8EfGXZucFURQGfA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8ojbrKY8EfGXZucFURQGfA">
        <name xmi:type="expression:Expression" xmi:id="_8ojbraY8EfGXZucFURQGfA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8ojbrqY8EfGXZucFURQGfA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_Q6IGTKY3EfGXZucFURQGfA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_Q6IGTaY3EfGXZucFURQGfA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_Q6IGTqY3EfGXZucFURQGfA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_Q6IGT6Y3EfGXZucFURQGfA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_Q6IGUKY3EfGXZucFURQGfA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_Q6IGUaY3EfGXZucFURQGfA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_Q6IGUqY3EfGXZucFURQGfA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_Q6IGU6Y3EfGXZucFURQGfA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_Q6IGVKY3EfGXZucFURQGfA" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_Q6IGVaY3EfGXZucFURQGfA" type="Process" element="_Q6IGIKY3EfGXZucFURQGfA" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_8olQ0KY8EfGXZucFURQGfA" type="2007" element="_8odVAKY8EfGXZucFURQGfA">
      <children xmi:type="notation:DecorationNode" xmi:id="_8olQ1aY8EfGXZucFURQGfA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_8olQ1qY8EfGXZucFURQGfA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_AX6XYKY_EfGXZucFURQGfA" type="3007" element="_AX4iMKY_EfGXZucFURQGfA">
          <children xmi:type="notation:DecorationNode" xmi:id="_AX7lgKY_EfGXZucFURQGfA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_AX7lgaY_EfGXZucFURQGfA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_jybIMKY_EfGXZucFURQGfA" type="3002" element="_jyTMYKY_EfGXZucFURQGfA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_jycWUKY_EfGXZucFURQGfA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_jycWUaY_EfGXZucFURQGfA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jybIMaY_EfGXZucFURQGfA" x="118" y="65"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_QPxLcKZAEfGXZucFURQGfA" type="3005" element="_QPvWQKZAEfGXZucFURQGfA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_QPyZkKZAEfGXZucFURQGfA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QPxLcaZAEfGXZucFURQGfA" x="251" y="84" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_B-aPkKZJEfGXZucFURQGfA" type="3005" element="_B-ZogKZJEfGXZucFURQGfA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_B-a2oKZJEfGXZucFURQGfA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_B-aPkaZJEfGXZucFURQGfA" x="916" y="64" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_AX6XYaY_EfGXZucFURQGfA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_AX6XYqY_EfGXZucFURQGfA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_AX6XY6Y_EfGXZucFURQGfA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_AX7lgqY_EfGXZucFURQGfA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AX6XZKY_EfGXZucFURQGfA" x="188" y="98"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_I-LCkKY_EfGXZucFURQGfA" type="3007" element="_I-J0cKY_EfGXZucFURQGfA">
          <children xmi:type="notation:DecorationNode" xmi:id="_I-LClaY_EfGXZucFURQGfA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_I-LClqY_EfGXZucFURQGfA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_wxtzsKZAEfGXZucFURQGfA" type="3005" element="_wxtMoKZAEfGXZucFURQGfA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_wxtzsqZAEfGXZucFURQGfA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wxtzsaZAEfGXZucFURQGfA" x="211" y="24" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XZpl8KZFEfGXZucFURQGfA" type="3005" element="_XZo-4KZFEfGXZucFURQGfA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_XZpl8qZFEfGXZucFURQGfA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XZpl8aZFEfGXZucFURQGfA" x="822" y="45" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_WxLl0KZHEfGXZucFURQGfA" type="3027" element="_WxIigKZHEfGXZucFURQGfA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_WxMM4KZHEfGXZucFURQGfA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WxLl0aZHEfGXZucFURQGfA" x="55" y="138" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vO5R46ZHEfGXZucFURQGfA" type="3008" element="_vO4q0KZHEfGXZucFURQGfA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_vO5R5aZHEfGXZucFURQGfA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_vO5R5qZHEfGXZucFURQGfA" x="1" y="-55"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vO5R5KZHEfGXZucFURQGfA" x="611" y="73"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_I-LCkaY_EfGXZucFURQGfA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_I-LCkqY_EfGXZucFURQGfA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_I-LCk6Y_EfGXZucFURQGfA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_I-LCl6Y_EfGXZucFURQGfA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_I-LClKY_EfGXZucFURQGfA" x="48" y="250" width="777" height="277"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_NW-14KY_EfGXZucFURQGfA" type="3007" element="_NW-O0KY_EfGXZucFURQGfA">
          <children xmi:type="notation:DecorationNode" xmi:id="_NW-15aY_EfGXZucFURQGfA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_NW-15qY_EfGXZucFURQGfA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_tkrvoKZDEfGXZucFURQGfA" type="3005" element="_tkp6cKZDEfGXZucFURQGfA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_tksWsKZDEfGXZucFURQGfA" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_4C68EKfjEfGXZucFURQGfA" type="3043" element="_4Cca8KfjEfGXZucFURQGfA" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_4C9_YKfjEfGXZucFURQGfA" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_4C_NgKfjEfGXZucFURQGfA" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4C68EafjEfGXZucFURQGfA"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tkrvoaZDEfGXZucFURQGfA" x="194" y="107" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_EhM5QKZFEfGXZucFURQGfA" type="3008" element="_EhLrIKZFEfGXZucFURQGfA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_EhM5QqZFEfGXZucFURQGfA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_EhM5Q6ZFEfGXZucFURQGfA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EhM5QaZFEfGXZucFURQGfA" x="612" y="167"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XnSucKZHEfGXZucFURQGfA" type="3027" element="_XnSHYKZHEfGXZucFURQGfA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_XnSucqZHEfGXZucFURQGfA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XnSucaZHEfGXZucFURQGfA" x="384" y="119" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_mhqKEKZJEfGXZucFURQGfA" type="3005" element="_mho78KZJEfGXZucFURQGfA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_mhqxIKZJEfGXZucFURQGfA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mhqKEaZJEfGXZucFURQGfA" x="1340" y="105" width="144" height="72"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_NW-14aY_EfGXZucFURQGfA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_NW-14qY_EfGXZucFURQGfA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_NW-146Y_EfGXZucFURQGfA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_NW-156Y_EfGXZucFURQGfA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NW-15KY_EfGXZucFURQGfA" x="48" y="527" width="1677" height="295"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_P_qIUKY_EfGXZucFURQGfA" type="3007" element="_P_phQKY_EfGXZucFURQGfA">
          <children xmi:type="notation:DecorationNode" xmi:id="_P_qIVaY_EfGXZucFURQGfA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_P_qIVqY_EfGXZucFURQGfA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_hddF0KZIEfGXZucFURQGfA" type="3027" element="_hdcewKZIEfGXZucFURQGfA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_hddF0qZIEfGXZucFURQGfA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hddF0aZIEfGXZucFURQGfA" x="804" y="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XqeTYKZJEfGXZucFURQGfA" type="3027" element="_XqdFQKZJEfGXZucFURQGfA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_XqeTYqZJEfGXZucFURQGfA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XqeTYaZJEfGXZucFURQGfA" x="1106" y="78" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_yiNx6KZJEfGXZucFURQGfA" type="3027" element="_yiNK0KZJEfGXZucFURQGfA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_yiNx6qZJEfGXZucFURQGfA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yiNx6aZJEfGXZucFURQGfA" x="1436" y="46"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_3eF2AKZJEfGXZucFURQGfA" type="3003" element="_3eEn4KZJEfGXZucFURQGfA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_3eF2AqZJEfGXZucFURQGfA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_3eF2A6ZJEfGXZucFURQGfA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3eF2AaZJEfGXZucFURQGfA" x="1638" y="70"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_P_qIUaY_EfGXZucFURQGfA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_P_qIUqY_EfGXZucFURQGfA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_P_qIU6Y_EfGXZucFURQGfA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_P_qvYKY_EfGXZucFURQGfA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_P_qIVKY_EfGXZucFURQGfA" x="48" y="600" width="777" height="250"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_8olQ0aY8EfGXZucFURQGfA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_8olQ0qY8EfGXZucFURQGfA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_8olQ06Y8EfGXZucFURQGfA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_8olQ16Y8EfGXZucFURQGfA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8olQ1KY8EfGXZucFURQGfA" width="1850" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_Q6IGbaY3EfGXZucFURQGfA"/>
    <edges xmi:type="notation:Connector" xmi:id="_RMG34KZAEfGXZucFURQGfA" type="4001" element="_RMEboKZAEfGXZucFURQGfA" source="_jybIMKY_EfGXZucFURQGfA" target="_QPxLcKZAEfGXZucFURQGfA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_RMHe8qZAEfGXZucFURQGfA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RMHe86ZAEfGXZucFURQGfA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RMHe8KZAEfGXZucFURQGfA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RMHe8aZAEfGXZucFURQGfA" points="[-7, -2, -170, -26]$[140, 21, -23, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_RMJUIKZAEfGXZucFURQGfA" id="(1.0,0.9333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_RMJUIaZAEfGXZucFURQGfA" id="(0.23,0.44)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3-DekKZAEfGXZucFURQGfA" type="4001" element="_3-C3gKZAEfGXZucFURQGfA" source="_QPxLcKZAEfGXZucFURQGfA" target="_wxtzsKZAEfGXZucFURQGfA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3-EFoKZAEfGXZucFURQGfA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3-EFoaZAEfGXZucFURQGfA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3-DekaZAEfGXZucFURQGfA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3-DekqZAEfGXZucFURQGfA" points="[-12, 32, 65, -180]$[-84, 200, -7, -12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_3-FTwKZAEfGXZucFURQGfA" id="(0.2916666666666667,0.9166666666666666)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_3-FTwaZAEfGXZucFURQGfA" id="(0.43,0.24)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2gWVAKZBEfGXZucFURQGfA" type="4001" element="_2gVt8KZBEfGXZucFURQGfA" source="_wxtzsKZAEfGXZucFURQGfA" target="_WxLl0KZHEfGXZucFURQGfA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2gWVA6ZBEfGXZucFURQGfA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2gWVBKZBEfGXZucFURQGfA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2gWVAaZBEfGXZucFURQGfA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2gWVAqZBEfGXZucFURQGfA" points="[0, 6, -103, 0]$[96, 2, -7, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2gXjIKZBEfGXZucFURQGfA" id="(1.0,0.3125)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2gXjIaZBEfGXZucFURQGfA" id="(0.13333333333333333,0.06666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cA-WYKZFEfGXZucFURQGfA" type="4001" element="_cA420KZFEfGXZucFURQGfA" source="_EhM5QKZFEfGXZucFURQGfA" target="_XZpl8KZFEfGXZucFURQGfA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cA-WY6ZFEfGXZucFURQGfA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cA-WZKZFEfGXZucFURQGfA" x="-5" y="-14"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cA-WYaZFEfGXZucFURQGfA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cA-WYqZFEfGXZucFURQGfA" points="[-19, -30, -246, 371]$[-19, -214, -246, 187]$[52, -214, -175, 187]$[52, -401, -175, 0]$[167, -401, -60, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cBFEEKZFEfGXZucFURQGfA" id="(1.0,0.7441860465116279)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MuvQgKZHEfGXZucFURQGfA" type="4001" element="_Mus0QKZHEfGXZucFURQGfA" source="_WxLl0KZHEfGXZucFURQGfA" target="_tkrvoKZDEfGXZucFURQGfA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Muv3kqZHEfGXZucFURQGfA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Muv3k6ZHEfGXZucFURQGfA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Muv3kKZHEfGXZucFURQGfA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Muv3kaZHEfGXZucFURQGfA" points="[-120, 1, 79, -282]$[-143, 1, 56, -282]$[-143, 153, 56, -130]$[-193, 153, 6, -130]$[-193, 275, 6, -8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Muy64KZHEfGXZucFURQGfA" id="(1.0,0.48333333333333334)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Muy64aZHEfGXZucFURQGfA" id="(0.7916666666666666,0.13333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qkIL4KZHEfGXZucFURQGfA" type="4001" element="_qkHk0KZHEfGXZucFURQGfA" source="_XnSucKZHEfGXZucFURQGfA" target="_EhM5QKZFEfGXZucFURQGfA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qkIy8KZHEfGXZucFURQGfA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qkIy8aZHEfGXZucFURQGfA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qkIL4aZHEfGXZucFURQGfA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qkIL4qZHEfGXZucFURQGfA" points="[-9, 43, 16, -77]$[-25, 116, 0, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qkKoIKZHEfGXZucFURQGfA" id="(0.7928571428571428,0.9714285714285714)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qkKoIaZHEfGXZucFURQGfA" id="(0.5348837209302325,0.13953488372093023)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wHH6YKZHEfGXZucFURQGfA" type="4001" element="_wHHTUKZHEfGXZucFURQGfA" source="_XZpl8KZFEfGXZucFURQGfA" target="_vO5R46ZHEfGXZucFURQGfA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wHH6Y6ZHEfGXZucFURQGfA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wHH6ZKZHEfGXZucFURQGfA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wHH6YaZHEfGXZucFURQGfA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wHH6YqZHEfGXZucFURQGfA" points="[0, 0, -27, 111]$[25, -108, -2, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wHJIgKZHEfGXZucFURQGfA" id="(1.0,0.5666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wHJIgaZHEfGXZucFURQGfA" id="(0.3953488372093023,0.7906976744186046)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_9JgLkKZHEfGXZucFURQGfA" type="4001" element="_9JfkgKZHEfGXZucFURQGfA" source="_vO5R46ZHEfGXZucFURQGfA" target="_tkrvoKZDEfGXZucFURQGfA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_9JgLk6ZHEfGXZucFURQGfA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_9JgLlKZHEfGXZucFURQGfA" x="48" y="-14"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_9JgLkaZHEfGXZucFURQGfA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_9JgLkqZHEfGXZucFURQGfA" points="[-22, 15, 302, -223]$[-22, 29, 302, -209]$[-347, 29, -23, -209]$[-347, 208, -23, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_9JhZsKZHEfGXZucFURQGfA" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FnUFYKZIEfGXZucFURQGfA" type="4001" element="_FnCYkKZIEfGXZucFURQGfA" source="_vO5R46ZHEfGXZucFURQGfA" target="_wxtzsKZAEfGXZucFURQGfA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FnUscqZIEfGXZucFURQGfA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FnUsc6ZIEfGXZucFURQGfA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FnUscKZIEfGXZucFURQGfA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FnUscaZIEfGXZucFURQGfA" points="[-43, -10, 247, 54]$[-176, -10, 114, 54]$[-176, -54, 114, 10]$[-244, -54, 46, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FnV6kKZIEfGXZucFURQGfA" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FnV6kaZIEfGXZucFURQGfA" id="(0.7125,0.775)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oQQPUKZIEfGXZucFURQGfA" type="4001" element="_oQA-wKZIEfGXZucFURQGfA" source="_vO5R46ZHEfGXZucFURQGfA" target="_hddF0KZIEfGXZucFURQGfA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oQQ2YKZIEfGXZucFURQGfA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oQQ2YaZIEfGXZucFURQGfA" x="-74" y="-5"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oQQPUaZIEfGXZucFURQGfA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oQQPUqZIEfGXZucFURQGfA" points="[-22, 12, -220, -530]$[-22, 82, -220, -460]$[281, 82, 83, -460]$[281, 310, 83, -232]$[196, 310, -2, -232]$[196, 538, -2, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_oQSEgKZIEfGXZucFURQGfA" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_oQSEgaZIEfGXZucFURQGfA" id="(0.48,0.08)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_r9LNAKZIEfGXZucFURQGfA" type="4001" element="_r9DRMKZIEfGXZucFURQGfA" source="_EhM5QKZFEfGXZucFURQGfA" target="_hddF0KZIEfGXZucFURQGfA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_r9LNA6ZIEfGXZucFURQGfA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_r9LNBKZIEfGXZucFURQGfA" x="-57" y="-4"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_r9LNAaZIEfGXZucFURQGfA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_r9LNAqZIEfGXZucFURQGfA" points="[-27, 11, 71, -252]$[-76, 263, 22, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_r9MbIKZIEfGXZucFURQGfA" id="(1.0,0.627906976744186)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_r9O3YKZIEfGXZucFURQGfA" id="(0.78,0.52)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MA-gs6ZJEfGXZucFURQGfA" type="4001" element="_MA-gsKZJEfGXZucFURQGfA" source="_hddF0KZIEfGXZucFURQGfA" target="_B-aPkKZJEfGXZucFURQGfA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MA_u0KZJEfGXZucFURQGfA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MA_u0aZJEfGXZucFURQGfA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MA-gtKZJEfGXZucFURQGfA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MA-gtaZJEfGXZucFURQGfA" points="[0, 0, -199, 551]$[200, -539, 1, 12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_MBA88KZJEfGXZucFURQGfA" id="(1.0,0.74)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_MBA88aZJEfGXZucFURQGfA" id="(0.825,0.7333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pYIn8qZJEfGXZucFURQGfA" type="4001" element="_pYIA4KZJEfGXZucFURQGfA" source="_XqeTYKZJEfGXZucFURQGfA" target="_mhqKEKZJEfGXZucFURQGfA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pYJPAKZJEfGXZucFURQGfA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pYJPAaZJEfGXZucFURQGfA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pYIn86ZJEfGXZucFURQGfA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pYIn9KZJEfGXZucFURQGfA" points="[0, 0, -96, 118]$[89, -113, -7, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_pYKdIKZJEfGXZucFURQGfA" id="(1.0,0.76)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_pYKdIaZJEfGXZucFURQGfA" id="(0.21428571428571427,0.8888888888888888)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_04DA06ZJEfGXZucFURQGfA" type="4001" element="_04DA0KZJEfGXZucFURQGfA" source="_mhqKEKZJEfGXZucFURQGfA" target="_yiNx6KZJEfGXZucFURQGfA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_04DA1qZJEfGXZucFURQGfA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_04DA16ZJEfGXZucFURQGfA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_04DA1KZJEfGXZucFURQGfA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_04DA1aZJEfGXZucFURQGfA" points="[0, 0, -67, -112]$[67, 106, 0, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_04E2AKZJEfGXZucFURQGfA" id="(1.0,0.5396825396825397)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_04E2AaZJEfGXZucFURQGfA" id="(0.06,0.16)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_9CkyQKZJEfGXZucFURQGfA" type="4001" element="_9CkLMKZJEfGXZucFURQGfA" source="_yiNx6KZJEfGXZucFURQGfA" target="_3eF2AKZJEfGXZucFURQGfA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_9CkyQ6ZJEfGXZucFURQGfA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_9CkyRKZJEfGXZucFURQGfA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_9CkyQaZJEfGXZucFURQGfA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_9CkyQqZJEfGXZucFURQGfA" points="[0, 6, -86, 0]$[86, 10, 0, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_9CkyRaZJEfGXZucFURQGfA" id="(1.0,0.62)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_9CkyRqZJEfGXZucFURQGfA" id="(0.5333333333333333,0.7666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FhEjQKfkEfGXZucFURQGfA" type="4001" element="_Fg5kIKfkEfGXZucFURQGfA" source="_4C68EKfjEfGXZucFURQGfA" target="_XnSucKZHEfGXZucFURQGfA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FhFKUKfkEfGXZucFURQGfA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FhFKUafkEfGXZucFURQGfA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FhEjQafkEfGXZucFURQGfA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FhEjQqfkEfGXZucFURQGfA" points="[0, -8, -117, 0]$[108, -6, -9, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FhINoKfkEfGXZucFURQGfA" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FhINoafkEfGXZucFURQGfA" id="(0.07857142857142857,0.7714285714285715)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PWgbMKuxEfGXZucFURQGfA" type="4001" element="_PWPVcKuxEfGXZucFURQGfA" source="_B-aPkKZJEfGXZucFURQGfA" target="_XqeTYKZJEfGXZucFURQGfA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PWplIKuxEfGXZucFURQGfA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PWqzQKuxEfGXZucFURQGfA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PWgbMauxEfGXZucFURQGfA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PWgbMquxEfGXZucFURQGfA" points="[0, 0, -100, -623]$[147, 620, 47, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_PXPbAKuxEfGXZucFURQGfA" id="(1.0,0.6)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
